package com.Mentats;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class SessionController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private SessionRepository sessionRepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewSession (@RequestParam String name
      , @RequestParam Integer sessionTime, @RequestParam Boolean yesnoComplete 
      , @RequestParam List<String> namesList, @RequestParam String notes
      , @RequestParam String imageLink) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    Session firstSession = new Session();
    firstSession.setName(name);
    firstSession.setSessionTime(sessionTime);
    firstSession.setYesNoComplete(yesnoComplete);
    firstSession.setNamesList(namesList);
    firstSession.setNotes(notes);
    firstSession.setImageLink(imageLink);
    sessionRepository.save(firstSession);
    return "Saved";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Session> getAllForSession() {
    // This returns a JSON or XML with the users
    return sessionRepository.findAll();
  }
}